version: '3'
services:
  fastapi:
    build: fastapi/
    platform: linux/amd64
    ports:
      - '5000:5000'
    volumes:
      - '/koster:/usr/src/app/koster'
      - './model_config:/data'
      - './uploads:/uploads'
    networks:
      - deploy_network
    container_name: fastapi
  streamlit:
    build: streamlit/
    platform: linux/amd64
    depends_on:
      - fastapi
    ports:
      - '8501:8501'
    volumes:
      - './model_config:/data'
      - './uploads:/uploads'
    networks:
      - deploy_network
    container_name: streamlit
networks:
  deploy_network:
    driver: bridge
